clc; clear; close all;

format long

%A = sin(2 * x) * cos(2 * x);
x = -2 * pi:pi / 100:2 * pi;
A = sin(2 * x) .* cos(2 * x);
anteg = trapz(x, A);
fprintf('\nA = Integral[-2 * pi, 2 * pi] sin(2 * x) * cos(2 * x) = %f \n', anteg);
subplot(3, 2, 1);
hold on;
plot(x, sin(2 * x));
plot(x, cos(2 * x), 'r');
legend('sin(2 * x)','cos(2 * x)');
xlabel('x');
ylabel('y');
title('A = sin(2 * x) * cos(2 * x)');
axis ([-2 * pi, 2 * pi, -1, 1]);
grid on;
hold off;

%B = sin(3 * x) * sin(2 * x);
x = -2 * pi:pi / 100:2 * pi;
B = sin(2 * x) .* cos(2 * x);
anteg = trapz(x, B);
fprintf('\nB = Integral[-2 * pi, 2 * pi] sin(3 * x) * sin(2 * x) = %f \n', anteg);
subplot(3, 2, 2);
hold on;
plot(x, sin(3 * x));
plot(x, sin(2 * x), 'r');
legend('sin(3 * x)','sin(2 * x)');
xlabel('x');
ylabel('y');
title('B = sin(3 * x) * sin(2 * x)');
axis ([-2 * pi, 2 * pi, -1, 1]);
grid on;
hold off;

%C = sin(3 * x) * sin(3 * x);
x = -2 * pi:pi / 100:2 * pi;
C = sin(3 * x) .* sin(3 * x);
anteg = trapz(x, C);
fprintf('\nC = Integral[-2 * pi, 2 * pi] sin(3 * x) * sin(3 * x) = %f \n', anteg);
subplot(3, 2, 3);
hold on;
plot(x, sin(3 * x));
plot(x, sin(3 * x), 'r');
legend('sin(3 * x)','sin(3 * x)');
xlabel('x');
ylabel('y');
title('C = sin(3 * x) * sin(3 * x)');
axis ([-2 * pi, 2 * pi, -1, 1]);
grid on;
hold off;

%D = sin(3 * x) * cos(2 * x);
x = -pi:pi / 100:pi;
D = sin(3 * x) .* cos(2 * x);
anteg = trapz(x, D);
fprintf('\nD = Integral[pi, pi] sin(3 * x) * cos(2 * x) = %f \n', anteg);
subplot(3, 2, 4);
hold on;
plot(x, sin(3 * x));
plot(x, cos(2 * x), 'r');
legend('sin(3 * x)','cos(2 * x)');
xlabel('x');
ylabel('y');
title('D = sin(3 * x) * cos(2 * x)');
axis ([-pi,pi, -1, 1]);
grid on;
hold off;

%E = cos(3 * x) * cos(2 * x);
x = -pi:pi / 100:pi;
E = cos(3 * x) .* cos(2 * x);
anteg = trapz(x, E);
fprintf('\nE = Integral[-pi, pi] cos(3 * x) * cos(2 * x) = %f \n', anteg);
subplot(3, 2, 5);
hold on;
plot(x, cos(3 * x));
plot(x, cos(2 * x), 'r');
legend('cos(3 * x)','cos(2 * x)');
xlabel('x');
ylabel('y');
title('E = cos(3 * x) * cos(2 * x)');
axis ([-pi, pi, -1, 1]);
grid on;
hold off;

%F = cos(2 * x) * cos(2 * x);
x = -pi:pi / 100:pi;
F = cos(2 * x) .* cos(2 * x);
anteg = trapz(x, F);
fprintf('\nF = Integral[-pi, pi] cos(2 * x) * cos(2 * x) = %f \n', anteg);
subplot(3, 2, 6);
hold on;
plot(x, cos(2 * x));
plot(x, cos(2 * x), 'r');
legend('cos(2 * x)','cos(2 * x)');
xlabel('x');
ylabel('y');
title('E = cos(2 * x) * cos(2 * x)');
axis ([-pi, pi, -1, 1]);
grid on;
hold off;
